services:
  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeper_data:/data
      - zookeper_log:/datalog

  kafka:
    image: bitnami/kafka:2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper

  gateway:
    image: gateway:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  wallet:
    image: wallet:0.1.0-SNAPSHOT
    volumes:
      - rocksdb_data:/opt/docker/rocksdb
    depends_on:
      - kafka

volumes:
  zookeper_data:
    driver: local
  zookeper_log:
    driver: local
  kafka_data:
    driver: local
  rocksdb_data:
    driver: local
